# Generated by Django 4.0.5 on 2022-07-29 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractionApp', '0005_alter_attractionmodels_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bigRouteModels',
            fields=[
                ('routeId', models.AutoField(primary_key=True, serialize=False, verbose_name='route id')),
                ('routeName', models.CharField(max_length=128, verbose_name='route name')),
                ('routeDate', models.DateField(auto_now_add=True, verbose_name='publish time')),
                ('routeImg', models.ImageField(default='/media/upload/user/home.jpg', upload_to='upload/route/', verbose_name='route img')),
                ('routeLike', models.IntegerField(default=0, verbose_name='how many person liked')),
                ('routeComment', models.IntegerField(default=0, verbose_name='how many person commented')),
                ('routeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='belong to which user')),
            ],
            options={
                'verbose_name_plural': 'Big Route',
            },
        ),
        migrations.CreateModel(
            name='likeModels',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False, verbose_name='like Id')),
                ('likeRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeApp.bigroutemodels', verbose_name='like route id')),
                ('likeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='like poster id')),
            ],
            options={
                'verbose_name_plural': 'like table',
            },
        ),
        migrations.CreateModel(
            name='dayRouteModels',
            fields=[
                ('dayRouteId', models.AutoField(primary_key=True, serialize=False, verbose_name='day route id')),
                ('dayRouteAttraction', models.ManyToManyField(to='attractionApp.attractionmodels')),
                ('dayRouteCity', models.ManyToManyField(to='attractionApp.citymodels')),
                ('dayRouteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='belong to which user')),
                ('dayRoutetoBigRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeApp.bigroutemodels', verbose_name='below to which big route')),
            ],
            options={
                'verbose_name_plural': 'Day Route',
            },
        ),
        migrations.CreateModel(
            name='commentModels',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False, verbose_name='comment id')),
                ('commentText', models.TextField(verbose_name='comment content')),
                ('commentTime', models.DateTimeField(auto_now_add=True)),
                ('commentRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeApp.bigroutemodels', verbose_name='belong to which route')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='below which user')),
            ],
        ),
    ]
