# Generated by Django 4.0.5 on 2022-08-07 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractionApp', '0008_alter_regionmodels_regionname'),
        ('routeApp', '0002_bigroutemodels_routeday'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayroutemodels',
            name='dayRouteNumber',
            field=models.IntegerField(default=0, verbose_name='day number'),
        ),
        migrations.CreateModel(
            name='recommendModels',
            fields=[
                ('recommendBigRoute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='routeApp.bigroutemodels')),
                ('recommendCategory', models.ManyToManyField(to='attractionApp.categorymodels')),
                ('recommendRegion', models.ManyToManyField(to='attractionApp.regionmodels')),
            ],
            options={
                'verbose_name_plural': 'recommend table',
            },
        ),
        migrations.CreateModel(
            name='M2MRecommendtoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeApp.recommendmodels', verbose_name='which recommend')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractionApp.regionmodels', verbose_name='which region')),
            ],
            options={
                'verbose_name_plural': 'M2M recommend - region',
            },
        ),
        migrations.CreateModel(
            name='M2MRecommendtoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractionApp.categorymodels', verbose_name='which category')),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeApp.recommendmodels', verbose_name='which recommend')),
            ],
            options={
                'verbose_name_plural': 'M2M recommend - category',
            },
        ),
        migrations.CreateModel(
            name='dayRCModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayRoute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeApp.dayroutemodels', verbose_name='dayRoute')),
                ('dayRouteCity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractionApp.citymodels', verbose_name='day_route_city')),
            ],
            options={
                'verbose_name_plural': 'M2M dayRoute - city',
            },
        ),
    ]
