# Generated by Django 4.0.5 on 2022-08-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeApp', '0003_dayroutemodels_dayroutenumber_recommendmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m2mrecommendtoregion',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='m2mrecommendtoregion',
            name='region',
        ),
        migrations.DeleteModel(
            name='M2MRecommendtoCategory',
        ),
        migrations.DeleteModel(
            name='M2MRecommendtoRegion',
        ),
    ]
