# Generated by Django 4.0.5 on 2022-08-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeApp', '0004_remove_m2mrecommendtoregion_recommend_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dayRCModels',
        ),
    ]
