# Generated by Django 4.0.5 on 2022-07-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodels',
            name='cityRegion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='attractionApp.regionmodels', verbose_name='city region'),
        ),
    ]
