# Generated by Django 4.0.5 on 2022-07-29 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractionApp', '0004_alter_attractionmodels_attractionlat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractionmodels',
            options={'verbose_name_plural': 'attraction'},
        ),
        migrations.AlterModelOptions(
            name='categorymodels',
            options={'verbose_name_plural': 'category'},
        ),
        migrations.AlterModelOptions(
            name='citymodels',
            options={'verbose_name_plural': 'city'},
        ),
        migrations.AlterModelOptions(
            name='regionmodels',
            options={'verbose_name_plural': 'region'},
        ),
    ]
