# Generated by Django 4.0.5 on 2022-07-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractionApp', '0005_alter_attractionmodels_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionmodels',
            name='attractionTrueId',
            field=models.CharField(default='luoyongsen', max_length=128, verbose_name='attraction true id'),
        ),
        migrations.AddField(
            model_name='citymodels',
            name='cityTrueId',
            field=models.CharField(default='luoyongsen', max_length=128, verbose_name='city true id'),
        ),
    ]
