# Generated by Django 4.0.5 on 2022-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractionApp', '0006_attractionmodels_attractiontrueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodels',
            name='regionName',
            field=models.CharField(max_length=3, verbose_name='region name'),
        ),
    ]
