# Generated by Django 4.0.5 on 2022-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractionApp', '0007_alter_regionmodels_regionname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodels',
            name='regionName',
            field=models.CharField(max_length=128, verbose_name='region name'),
        ),
    ]
